### ISSUE TITLE
Issue on playing songs

### ISSUE THREAD

**Issue by Trynight** [Krutyi-4el/DandelionMusic#30] opened 2023-03-01 17:37 UTC
Hi! From this morning the bot doesn't want to reproduce music.. when you give to him the command play with the song name, it will appear on discord that the bot is writing but nothing happens... the bot just join the vocal channel.

This is the error on the terminal:

`Startup Complete
Task was destroyed but it is pending!
task: <Task pending name='pycord: on_message' coro=<Client._run_event() running at /usr/local/lib/python3.8/dist-packages/discord/client.py:378> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_read_done(8)(), <TaskWakeupMethWrapper object at 0x7ff316c16310>()]>>
Playing megaride
Ignoring exception in command play:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 178, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/DingoLingo/musicbot/commands/music.py", line 43, in _play_song
    song = await audiocontroller.process_song(track)
  File "/root/DingoLingo/musicbot/audiocontroller.py", line 400, in process_song
    await self.play_song(song)
  File "/root/DingoLingo/musicbot/audiocontroller.py", line 338, in play_song
    self.guild.voice_client.play(
  File "/usr/local/lib/python3.8/dist-packages/discord/voice_client.py", line 658, in play
    raise ClientException("Not connected to voice.")
discord.errors.ClientException: Not connected to voice.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 347, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 950, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 187, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientException: Not connected to voice.
`

**Comment by Krutyi-4el** [comment] 2023-03-02 14:02
I can't reproduce the issue. What configuration do you use? Are you sure there's no second instance of the bot running?

**Comment by Krutyi-4el** [comment] 2023-03-10 15:19
I was listening to music for ~30 minutes and it suddenly stopped. When I stopped the music and tried to play again, it has thrown me `Not connected to voice.` error. However, `d!reset` fixed it. Is that how you got this error?

**Comment by StonebanksYT** [comment] 2023-03-24 12:40
Im having the same issue. It happened randomly and the bot was working fine for many days now. It just connects to the voice channel but does not play anything and the error says not connected to voice. Is there any fix plz?

**Comment by StonebanksYT** [comment] 2023-03-24 12:52
Never mind I updated the version of the bot and it works fine now. 

> Im having the same issue. It happened randomly and the bot was working fine for many days now. It just connects to the voice channel but does not play anything and the error says not connected to voice. Is there any fix plz?

**Comment by SonyUSA** [comment] 2023-03-24 19:45
Hello! I just downloaded this bot and am running into the same thing!

I got it playing fine but after the last song in queue stopped, after adding a new one, the bot will either show as typing something and then nothing further will happen (a message never appears) or sometimes it will show that it's playing a song but then won't actually play it... I'm using the standalone launcher/exe and saw some errors once but accidentally closed the window... something like "next event -20 | next event -21" but that probably doesn't help you.

**Comment by SonyUSA** [comment] 2023-03-24 19:48
Ah, after waiting a bit the bot suddenly spit out:
"Command raised an exception: TypeError: 'NoneType' object is not subscriptable" then suddenly started playing the song (from youtube).

**Comment by SonyUSA** [comment] 2023-03-24 19:52
![image](https://user-images.githubusercontent.com/17078864/227625889-65d599e7-7039-4e86-80e3-abf57fe8ff09.png)

**Comment by Krutyi-4el** [comment] 2023-03-25 16:43
> TypeError: 'NoneType' object is not subscriptable"

Unfortunately, that's not enough to identify the issue. I'd appreciate if you shared full traceback.

As for TLS errors, seems to be "connection reset by peer" thing. I was also getting a lot of those but it didn't affect the bot. Furthermore, I don't think it's even fixable unless we figure out how to trick YouTube more.

**Comment by SonyUSA** [comment] 2023-03-26 04:42
> > TypeError: 'NoneType' object is not subscriptable"
> 
> Unfortunately, that's not enough to identify the issue. I'd appreciate if you shared full traceback.

Is this possible with the standalone .exe ?

**Comment by Krutyi-4el** [comment] 2023-03-26 07:00
Yes, it should show full tracebacks. If it doesn't, open another issue regarding that.

**Comment by Veriosis72** [comment] 2023-04-02 04:03
Had the same issue, try updating py-cord and other modules just in case. Fixed it for me

**Comment by Krutyi-4el** [comment] 2023-04-02 15:18
@Veriosis72 `requirements.txt` already has the latest (or almost) versions. Which ones do you have?

**Comment by veriosis** [comment] 2023-04-02 21:21
> @Veriosis72 `requirements.txt` already has the latest (or almost) versions. Which ones do you have?

Well originally when I had the issue, pycord was on v2.3.2 but once I updated to v2.4.1 everything was working as usual. I read there was some update discord pushed out in March about voice connections, so that might've been what broke the bot for a lot of people.  https://github.com/Pycord-Development/pycord/issues/1954

**Comment by Krutyi-4el** [comment] 2023-06-17 20:32
Is anyone still experiencing this issue or it can be marked as resolved?

**Closed** 2023-07-22 02:41 UTC
