### ISSUE TITLE
Not playing music

### ISSUE THREAD

**Issue by kaanalp28** [Krutyi-4el/DandelionMusic#39] opened 2023-03-25 19:48 UTC
I've modified the bot a bit, but not necessarily on the music plugin, just added other cogs.
The thing is, when I try to play music, for the first few times, it just connects to the VC but does nothing else (No errors in terminal, no response in discord). After more tries, it gives this error:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/96485263/227738364-7cb4cb14-7bc5-4788-af74-89f9628189a3.png">
It says that the bot is not connected to voice, which it IS connected to.
<img width="192" alt="image" src="https://user-images.githubusercontent.com/96485263/227738423-0f9ba6b8-e936-4c10-8114-e561f0305f15.png">
Clearly its in the music channel.

No idea what causes this, can anyone help me with this?

**Comment by Krutyi-4el** [comment] 2023-03-25 20:02
Unfortunately, I don't have an idea either. But this issue is duplicate of #30, so I'm closing it. Please share any additional info there.

**Closed by Krutyi-4el** 2023-03-25 20:02 UTC

**Comment by kaanalp28** [comment] 2023-03-26 05:38
Ok, if i get any additional info, i will share it. Meanwhile, to solve the problem, i tried the newest version, and it works just fine, but is there a way to get back the console? I mean whit the current console that says "press ctrl c to close", i cant see any info. I liked the idea of closing the console and it running in the background, so i still want that feature, but is there any way so that if i don't close it, it shows me the console that shows the info? Thanks!

**Comment by Krutyi-4el** [comment] 2023-03-26 07:13
> but is there any way so that if i don't close it, it shows me the console that shows the info?

That was like the main idea. Can you please open new issue giving more information (whether you are running `.py` or `.exe`, your OS and Python version etc.)?

**Comment by kaanalp28** [comment] 2023-03-26 09:11
Update: It works now.
I re-installed some libraries, but idk which one affected this.
It just started working out of nowhere. (The old version that i had)

Btw, I always run the .py one.

Now, abt the new version... It stopped working (gives the same error), -i dont understand how the old one can work but the new one cant- and it doesnt work with slash commands (ive enabled slash commands in config, do i need to reset a cache or smthng?? bc i ran it once before changing the config) and i still cant see the OG terminal, just the ctrl C thingy. also, once i close the window, i cant close the bot, and, when i open a new one, it stacks up so every response is double, triple, etc. 

Now, i have no idea why it stopped working, no idea why it started working again (new one), and dont know what to do. (can this happen again in the future??)

I use win 11, and python 3.10.10

**Comment by Krutyi-4el** [comment] 2023-03-26 10:53
As I said, the problem wasn't resolved yet.

> it doesnt work with slash commands

You need to wait for ten minutes or so. Also make sure the bot has commands scope on the server.

> i still cant see the OG terminal, just the ctrl C thingy

Do you use powershell or cmd?
